In [177]:
import pandas as pd

In [68]:
# Load table of all images
allimages = pd.read_csv("Tables/All_Subjects_All_Images_20Feb2026.csv")

In [158]:
len(allimages[allimages.modality=="MRI"])

230002

In [160]:
temp = allimages[allimages.image_type=='Pre-processed']
temp[(temp.phase=="ADNI 3")&temp.image_description.str.contains("T1 ")&(temp.modality=="MRI")]

,image_id,subject_id,phase,study_id,modality,image_type,image_visit,image_date,image_description,upload_date,file_format,structure,laterality
273807,11380943,127_S_1427,ADNI 3,115027,MRI,Pre-processed,init,2017-09-06,Reoriented T1 Image,2025-07-24,NIfTI,Brain,Both
273808,11380944,127_S_1427,ADNI 3,115027,MRI,Pre-processed,init,2017-09-06,T1 Brain Mask,2025-07-24,NIfTI,Brain,Both
273809,11380949,127_S_1427,ADNI 3,115027,MRI,Pre-processed,init,2017-09-06,T1 MUSE segmentation,2025-07-24,NIfTI,Brain,Both
273819,11386554,127_S_1427,ADNI 3,127633,MRI,Pre-processed,y1,2018-10-12,Reoriented T1 Image,2025-07-28,NIfTI,Brain,Both
273820,11386556,127_S_1427,ADNI 3,127633,MRI,Pre-processed,y1,2018-10-12,T1 Brain Mask,2025-07-28,NIfTI,Brain,Both
...,...,...,...,...,...,...,...,...,...,...,...,...,...
335985,11365077,035_S_7115,ADNI 3,218809,MRI,Pre-processed,sc,2022-11-15,T1 Brain Mask,2025-07-23,NIfTI,Brain,Both
335986,11365082,035_S_7115,ADNI 3,218809,MRI,Pre-processed,sc,2022-11-15,T1 MUSE segmentation,2025-07-23,NIfTI,Brain,Both
336023,11365090,082_S_7117,ADNI 3,219059,MRI,Pre-processed,sc,2022-11-03,Reoriented T1 Image,2025-07-23,NIfTI,Brain,Both
336024,11365095,082_S_7117,ADNI 3,219059,MRI,Pre-processed,sc,2022-11-03,T1 Brain Mask,2025-07-23,NIfTI,Brain,Both
336025,11365107,082_S_7117,ADNI 3,219059,MRI,Pre-processed,sc,2022-11-03,T1 MUSE segmentation,2025-07-23,NIfTI,Brain,Both

In [10]:
mris = allimages[
    (allimages.modality=="MRI")&
    (allimages.image_type=="Original")
    ]

In [21]:
mris.image_description.value_counts()[:50]

image_description
3 Plane Localizer                      12014
localizer                               7604
Axial 3D ME T2 GRE (MSV21)              7183
3-plane localizer                       5823
MPRAGE                                  5558
Field Mapping                           5522
Axial PD-T2 TSE                         3942
Axial PD/T2 FSE                         3822
Localizer                               3288
Axial T2-FLAIR                          3041
Axial T2 Star                           2370
Sagittal 3D FLAIR                       2324
Axial 3TE T2 STAR                       2256
AXIAL_T2_STAR                           2075
MPRAGE GRAPPA2                          2061
MP-RAGE                                 2037
MPRAGE Repeat                           1961
B1-calibration Body                     1897
B1-calibration Head                     1866
MP-RAGE REPEAT                          1669
HighResHippo                            1487
B1-Calibration Body                     1479
B1-Calibration PA                       1461
Accelerated Sagittal MPRAGE             1445
HighResHippocampus                      1417
Calibration Scan                        1338
Field_mapping                           1221
Axial FLAIR                             1101
Sagittal 3D FLAIR (MSV22)                999
Accelerated Sagittal MPRAGE (MSV21)      948
Axial T2 TSE with Fat Sat                939
SURVEY                                   898
Axial T2-Star                            871
Head,3-P,2D,LOCALIZER                    870
HighResHippocampus (MSV21)               858
MPRAGE SENSE2                            856
Sagittal 3D T2 SPACE (MSV21)             793
Double_TSE                               711
Sag IR-SPGR                              689
Accelerated Sag IR-FSPGR                 683
LOC                                      669
ADNI_gre_field_mapping                   667
FSE PD/T2                                602
Axial Field Mapping                      570
Circle Scout                             550
Axial T2 STAR                            543
Sag IR-FSPGR                             430
3-pl T2* FGRE                            414
Accelerated SAG IR-SPGR                  414
Isotropic image                          410
Name: count, dtype: int64

In [22]:
mris.subject_id.value_counts()[-10:]

subject_id
404_S_10895    4
404_S_10853    4
404_S_10898    4
005_S_10446    3
381_S_10578    3
941_S_10010    3
100_S_10035    3
073_S_10228    3
005_S_10240    3
022_S_10055    2
Name: count, dtype: int64

In [23]:
mris34 = mris[(mris.phase=="ADNI 3")|(mris.phase=="ADNI 4")]
len(mris34)

37622

In [31]:
mris3 = mris[(mris.phase=="ADNI 3")]
len(mris3)

25313

In [32]:
mris3.image_description.value_counts()[:50]

image_description
3 Plane Localizer                                                  6648
Field Mapping                                                      4032
Sagittal 3D FLAIR                                                  2314
Axial 3TE T2 STAR                                                  2256
Accelerated Sagittal MPRAGE                                        1438
HighResHippocampus                                                 1410
Axial T2 Star                                                      1320
Axial Field Mapping                                                 570
Axial T2 STAR                                                       543
HighResHippo                                                        536
Calibration Scan                                                    375
Sagittal 3D Accelerated MPRAGE                                      353
HighResHippo Scan (Oblique - perpendicular to hippocampal tail      343
Accelerated Sag IR-FSPGR                                            310
Accelerated Sagittal IR-FSPGR                                       258
Accelerated Sagittal MPRAGE_ND                                      258
Axial 3TE T2 Star                                                   237
3TE Axial T2 Star                                                   186
Field Mapping phase R-L                                             174
Isotropic image                                                     148
AAHead_Scout_MPR_sag                                                136
AAHead_Scout                                                        121
HighResHippo Scan (Oblique - perpendicular to hippocampal tail)      79
Axial 3TE T2 STAR  straight no angle                                 72
COR HighResHippo                                                     66
Accelerated Sagittal MPRAGE Phase A-P                                59
Sagittal 3D FLAIR phase A-P                                          59
Axial T2 STAR phase R-L                                              58
HighResHippocampus Phase R-L                                         58
Axial Field Mapping 0 angle                                          58
Cal 8HRBRAIN                                                         54
SCOUT                                                                48
Field_Mapping                                                        39
Field Mapping_ND                                                     39
Field Mapping    straight no angle                                   36
Axial T2 Star (NO ANGLE)                                             33
Axial T2 0 angle Star                                                32
Sagittal 3D Accelerated 0 angle MPRAGE                               29
Sagittal 3D 0 angle FLAIR                                            29
Localizer                                                            25
SWI_Images                                                           24
mIP_Images(SW)                                                       24
Obl HighResHippo                                                     20
Axial 3D ME T2 GRE (MSV21)                                           20
Sag Accel IR-FSPGR                                                   19
localizer                                                            18
Axial Field Mapping straight                                         16
Field Mapping Phase Direction P>A                                    15
Cal RM:8HRBRAIN                                                      10
3_Plane_Localizer                                                     9
Name: count, dtype: int64

In [25]:
mris34.subject_id.nunique()

1796

In [29]:
mris34.subject_id.value_counts()[1000:1010]

subject_id
003_S_10158    14
073_S_10167    14
073_S_10172    14
941_S_10148    14
389_S_10140    14
022_S_10136    14
014_S_10180    14
073_S_10089    14
052_S_10242    14
016_S_10190    14
Name: count, dtype: int64

In [178]:
# Load table of diagnosis
diagnosis = pd.read_csv("Tables/All_Subjects_DXSUM_20Feb2026.csv")
diagnosis.USERDATE = diagnosis.USERDATE.apply(pd.to_datetime)
diagnosis34 = diagnosis[
    (diagnosis.PHASE=="ADNI3")
    ]

In [186]:
diagnosis_ = {}
for i in [1,"GO",2,3,4]:
    diagnosis_[i] = diagnosis[diagnosis.PHASE==f"ADNI{i}"]

In [197]:
for i in [1,"GO",2,3,4]:
    print(f"Count of patients in phase {i}: {diagnosis_[i].PTID.nunique()}")

p = [1,"GO",2,3,4]
for i in range(4):
    print(f"Count of patients in phase {p[i]} that didn't continue in phase {p[i+1]}: {diagnosis_[p[i]][~diagnosis_[p[i]].PTID.isin(diagnosis_[p[i+1]].PTID)].PTID.nunique()}")

Count of patients in phase 1: 819
Count of patients in phase GO: 338
Count of patients in phase 2: 1438
Count of patients in phase 3: 1376
Count of patients in phase 4: 1339
Count of patients in phase 1 that didn't continue in phase GO: 610
Count of patients in phase GO that didn't continue in phase 2: 41
Count of patients in phase 2 that didn't continue in phase 3: 1028
Count of patients in phase 3 that didn't continue in phase 4: 860

In [198]:
diagnosis.PTID.nunique()

3789

In [192]:
diagnosis[diagnosis.PTID=="007_S_6341"]

,PHASE,PTID,RID,VISCODE,VISCODE2,EXAMDATE,DIAGNOSIS,DXNORM,DXNODEP,DXMCI,...,DXODES,DXCONFID,ID,SITEID,USERDATE,USERDATE2,DD_CRF_VERSION_LABEL,LANGUAGE_CODE,HAS_QC_ERROR,update_stamp
10729,ADNI3,007_S_6341,6341,sc,sc,2018-04-30,2.0,NaN,NaN,NaN,...,NaN,NaN,41028,5,2018-05-04,2018-05-04,NaN,NaN,NaN,2018-05-04 22:38:16
10839,ADNI3,007_S_6341,6341,bl,bl,2018-06-07,2.0,NaN,NaN,NaN,...,NaN,NaN,46293,5,2018-06-08,2018-06-08,NaN,NaN,NaN,2018-06-08 22:37:32
11651,ADNI3,007_S_6341,6341,y1,m12,2019-06-11,2.0,NaN,NaN,NaN,...,NaN,NaN,86339,5,2019-06-18,2019-06-18,NaN,NaN,NaN,2019-06-18 09:50:36
12300,ADNI3,007_S_6341,6341,y2,m24,2020-08-19,2.0,NaN,NaN,NaN,...,NaN,NaN,117889,5,2020-08-24,2020-08-26,NaN,NaN,NaN,2020-08-27 04:16:42
12692,ADNI3,007_S_6341,6341,y3,m36,2021-07-19,3.0,NaN,NaN,NaN,...,NaN,NaN,138263,5,2021-07-21,2021-07-21,NaN,NaN,NaN,2021-07-22 04:17:49
13121,ADNI3,007_S_6341,6341,y4,m48,2022-05-24,3.0,NaN,NaN,NaN,...,NaN,NaN,157619,5,2022-05-31,2022-05-31,NaN,NaN,NaN,2022-06-01 04:18:49
13440,ADNI3,007_S_6341,6341,y5,m60,2023-05-16,3.0,NaN,NaN,NaN,...,NaN,NaN,175120,5,2023-05-17,2023-05-17,NaN,NaN,NaN,2023-05-18 04:20:28
13877,ADNI4,007_S_6341,6341,4_init,m72,2024-05-21,3.0,NaN,NaN,NaN,...,NaN,NaN,17265,7,2024-05-28,2024-05-28,v1,e,0.0,2024-05-29 01:39:34

In [84]:
allimages3 = allimages[(allimages.phase=="ADNI 3")&(allimages.modality=="MRI")]

In [46]:
cn = diagnosis34[diagnosis34.DIAGNOSIS==1.0][["PTID","USERDATE","DIAGNOSIS"]]
mci = diagnosis34[diagnosis34.DIAGNOSIS==2.0][["PTID","USERDATE","DIAGNOSIS"]]
ad = diagnosis34[diagnosis34.DIAGNOSIS==3.0][["PTID","USERDATE","DIAGNOSIS"]]

In [169]:
#### Transition patients
patients = pd.merge(mci,ad,on="PTID")
times = patients.groupby("PTID")["USERDATE_y"].max()-patients.groupby("PTID")["USERDATE_x"].min()
cleaned_times = times[times>pd.Timedelta(0)]
times

### always same diagnosis patients:
# patients = mci[(~mci.PTID.isin(cn.PTID))&(~mci.PTID.isin(ad.PTID))]
# times = patients.groupby("PTID")["USERDATE"].max()-patients.groupby("PTID")["USERDATE"].min()
# cleaned_times = times
# times

PTID
003_S_4354   1287 days
006_S_6252    552 days
006_S_6770   1350 days
007_S_4272   1817 days
007_S_4637    324 days
007_S_5265    385 days
007_S_6341   1839 days
012_S_6073   1808 days
014_S_2185    715 days
016_S_6800    607 days
016_S_6939    376 days
018_S_2155   1918 days
019_S_6483   1859 days
019_S_6668   1863 days
021_S_5237   1509 days
022_S_6863    601 days
023_S_4115   1475 days
023_S_6535   1175 days
027_S_6034   1739 days
027_S_6640    874 days
027_S_6788    852 days
033_S_6497   1150 days
033_S_7088    399 days
035_S_4114    733 days
035_S_7000    789 days
036_S_2380    900 days
036_S_4538   1049 days
037_S_0467    781 days
037_S_6222    937 days
041_S_4271    547 days
041_S_6731   1548 days
067_S_4782   1495 days
067_S_6529   1136 days
070_S_6911    433 days
098_S_0896    390 days
099_S_6632   1191 days
114_S_5047   2073 days
126_S_0605   1810 days
126_S_4891   1824 days
126_S_6724   1176 days
127_S_6241   1841 days
128_S_2130   1102 days
128_S_2220   1370 days
129_S_4422    762 days
129_S_6852    773 days
131_S_6805   1226 days
135_S_6411   1040 days
137_S_4862    878 days
153_S_6755   1876 days
168_S_6467    838 days
168_S_6634   1661 days
168_S_6908    859 days
305_S_6810   -552 days
941_S_4365   1814 days
941_S_6068   1825 days
941_S_6345    896 days
dtype: timedelta64[us]

In [176]:
diagnosis34[diagnosis34.PTID.isin(allimages3.subject_id)].PTID.nunique()

1150

In [164]:
len(cleaned_times)

394

In [157]:
visits = allimages3[allimages3.subject_id.isin(cleaned_times.index)]

In [162]:
visits.groupby("subject_id")["image_date"].unique().apply(len).mean()

np.float64(1.7741935483870968)

In [168]:
visits.groupby("subject_id")["image_date"].unique()

subject_id
002_S_4225                            [2018-11-12]
003_S_1074                            [2017-09-22]
003_S_6264                            [2018-06-04]
003_S_6833                            [2019-11-07]
006_S_6689                [2019-02-27, 2022-03-31]
                              ...
305_S_6850                [2020-01-29, 2021-02-23]
305_S_6881                            [2020-08-24]
341_S_6820                            [2019-09-25]
941_S_6854    [2020-02-14, 2021-04-05, 2022-02-22]
941_S_6962                [2021-07-13, 2022-06-29]
Name: image_date, Length: 124, dtype: object

In [159]:
times.mean()

Timedelta('453 days 02:48:18.701298')

In [117]:
diagnosis[diagnosis.PTID=="941_S_4100"]

,PHASE,PTID,RID,VISCODE,VISCODE2,EXAMDATE,DIAGNOSIS,DXNORM,DXNODEP,DXMCI,...,DXODES,DXCONFID,ID,SITEID,USERDATE,USERDATE2,DD_CRF_VERSION_LABEL,LANGUAGE_CODE,HAS_QC_ERROR,update_stamp
4486,ADNI2,941_S_4100,4100,v01,sc,2011-06-27,1.0,NaN,NaN,NaN,...,NaN,NaN,302,58,2011-07-05,NaN,NaN,NaN,NaN,2013-03-14 19:16:45
4603,ADNI2,941_S_4100,4100,v03,bl,2011-08-16,1.0,NaN,NaN,NaN,...,NaN,NaN,536,58,2011-08-22,NaN,NaN,NaN,NaN,2013-03-14 19:16:45
5876,ADNI2,941_S_4100,4100,v05,m06,2012-06-01,1.0,NaN,NaN,NaN,...,NaN,NaN,3084,58,2012-06-04,NaN,NaN,NaN,NaN,2013-03-14 19:16:46
6473,ADNI2,941_S_4100,4100,v11,m12,2012-08-31,1.0,NaN,NaN,NaN,...,NaN,NaN,4278,58,2012-10-05,NaN,NaN,NaN,NaN,2013-03-14 19:16:46
8780,ADNI2,941_S_4100,4100,v21,m24,2014-07-03,1.0,NaN,NaN,NaN,...,NaN,NaN,8896,58,2014-07-03,NaN,NaN,NaN,NaN,2014-07-03 19:16:58
9380,ADNI2,941_S_4100,4100,v41,m48,2015-08-28,2.0,NaN,NaN,NaN,...,NaN,NaN,10100,58,2015-09-01,NaN,NaN,NaN,NaN,2015-09-01 19:17:01
10296,ADNI3,941_S_4100,4100,init,m72,2017-10-26,2.0,NaN,NaN,NaN,...,NaN,NaN,18832,59,2017-11-01,2017-11-01,NaN,NaN,NaN,2017-11-01 22:28:13
11397,ADNI3,941_S_4100,4100,y1,m90,2018-11-19,2.0,NaN,NaN,NaN,...,NaN,NaN,73585,59,2019-01-16,2019-01-16,NaN,NaN,NaN,2021-07-29 04:17:59
13283,ADNI3,941_S_4100,4100,y4,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,165018,59,2022-09-07,2022-09-07,NaN,NaN,NaN,2022-09-08 04:19:08

In [39]:
diagnosis34.PTID.nunique()

2199

In [42]:
mrist1w = mris[
    mris.image_description.str.contains("RAGE")|
    mris.image_description.str.contains("SPGR")
    ]
len(mrist1w)

23875

In [45]:
mrist1w.image_description.value_counts()[:20]

image_description
MPRAGE                                 5558
MPRAGE GRAPPA2                         2061
MP-RAGE                                2037
MPRAGE Repeat                          1961
MP-RAGE REPEAT                         1669
Accelerated Sagittal MPRAGE            1445
Accelerated Sagittal MPRAGE (MSV21)     948
MPRAGE SENSE2                           856
Sag IR-SPGR                             689
Accelerated Sag IR-FSPGR                683
Sag IR-FSPGR                            430
Accelerated SAG IR-SPGR                 414
Sagittal 3D Accelerated MPRAGE          355
MPRAGE_GRAPPA2                          334
Accelerated Sag IR-SPGR                 280
MP-RAGE-Repeat                          268
Accelerated Sagittal IR-FSPGR           258
Accelerated Sagittal MPRAGE_ND          258
IR-FSPGR-Repeat                         164
IR-FSPGR                                154
Name: count, dtype: int64

In [47]:
len(allimages)

349508

In [49]:
mris34t1w = mris34[
    mris34.image_description.str.contains("RAGE")|
    mris34.image_description.str.contains("SPGR")
    ]
len(mris34t1w)

4199

In [126]:
mris34t1w

,image_id,subject_id,phase,study_id,modality,image_type,image_visit,image_date,image_description,upload_date,file_format,structure,laterality
439,901027,127_S_1427,ADNI 3,115027,MRI,Original,init,2017-09-06,Accelerated Sagittal IR-FSPGR,2017-09-06,DICOM,Brain,Both
468,1059960,127_S_1427,ADNI 3,127633,MRI,Original,y1,2018-10-12,Accelerated Sagittal IR-FSPGR,2018-10-15,DICOM,Brain,Both
481,1234305,127_S_1427,ADNI 3,143233,MRI,Original,y2,2019-09-30,Accelerated Sagittal IR-FSPGR,2019-09-30,DICOM,Brain,Both
1888,955206,007_S_1222,ADNI 3,119402,MRI,Original,init,2018-01-17,Accelerated Sagittal MPRAGE,2018-01-18,DICOM,Brain,Both
1904,1291745,007_S_1222,ADNI 3,149786,MRI,Original,y2,2020-02-18,Accelerated Sagittal MPRAGE,2020-02-18,DICOM,Brain,Both
...,...,...,...,...,...,...,...,...,...,...,...,...,...
349450,11427809,158_S_10782,ADNI 4,371686,MRI,Original,4_sc,2025-07-22,CS Sagittal MPRAGE (MSV22),2025-08-29,DICOM,Brain,Both
349467,11433172,158_S_10843,ADNI 4,371690,MRI,Original,4_sc,2025-07-18,Accelerated Sagittal MPRAGE (MSV21),2025-09-08,DICOM,Brain,Both
349468,11433173,158_S_10843,ADNI 4,371690,MRI,Original,4_sc,2025-07-18,CS Sagittal MPRAGE (MSV22),2025-09-08,DICOM,Brain,Both
349485,11448624,158_S_10850,ADNI 4,373514,MRI,Original,4_sc,2025-07-18,Accelerated Sagittal MPRAGE (MSV21),2025-09-25,DICOM,Brain,Both
349486,11448625,158_S_10850,ADNI 4,373514,MRI,Original,4_sc,2025-07-18,CS Sagittal MPRAGE (MSV22),2025-09-25,DICOM,Brain,Both

In [51]:
mris34t1w.subject_id.nunique()

1796

In [70]:
mris34t1w.image_date = mris34t1w.image_date.apply(pd.to_datetime)
span_counts34 = mris34t1w.groupby("subject_id")["image_date"].agg(lambda x:x.max()-x.min())

In [110]:
len(span_counts34[span_counts34>pd.Timedelta("1056 days")])

504

In [72]:
mrist1w.image_date = mrist1w.image_date.apply(pd.to_datetime)
span_counts = mrist1w.groupby("subject_id")["image_date"].agg(lambda x:x.max()-x.min())

In [108]:
len(span_counts[span_counts>pd.Timedelta("365 days")])

2056

In [83]:
biomark = pd.read_csv("Tables/All_Subjects_BIOMARK_20Feb2026.csv",low_memory=False)

In [84]:
biomark.update_stamp = biomark.update_stamp.apply(pd.to_datetime)
biomark_span = biomark.groupby("PTID")["update_stamp"].agg(lambda x:x.max()-x.min())

In [94]:
len(biomark_span[biomark_span>pd.Timedelta("360 days")])

1929

In [88]:
biomark34 = biomark[
    (biomark.PHASE=="ADNI3")|
    (biomark.PHASE=="ADNI4")
    ]

In [89]:
biomark34.update_stamp = biomark34.update_stamp.apply(pd.to_datetime)
biomark34_span = biomark34.groupby("PTID")["update_stamp"].agg(lambda x:x.max()-x.min())

In [100]:
len(biomark34_span[biomark34_span>pd.Timedelta("365 days")])

803

In [121]:
merged = pd.merge(biomark34_span,span_counts34,left_on="PTID",right_on="subject_id")

In [122]:
len(merged)

1581

In [125]:
t = pd.Timedelta("1095 days")
len(merged[(merged.update_stamp>t)&(merged.image_date>t)])

443

In [99]:
mris34t1w.image_visit.value_counts()

image_visit
sc        925
4_sc      777
y2        569
y1        474
4_init    409
init      388
y4        269
4_m12     198
y3        116
y5         37
4_m24      37
Name: count, dtype: int64

In [111]:
mris34t1w[mris34t1w.image_visit=="sc"]

,image_id,subject_id,phase,study_id,modality,image_type,image_visit,image_date,image_description,upload_date,file_format,structure,laterality
237514,1092019,341_S_6653,ADNI 3,130447,MRI,Original,sc,2018-12-19,Accelerated Sagittal MPRAGE,2018-12-19,DICOM,Brain,Both
237555,1118713,002_S_6652,ADNI 3,132824,MRI,Original,sc,2018-12-13,Accelerated Sagittal MPRAGE,2019-01-22,DICOM,Brain,Both
237614,1100512,027_S_6640,ADNI 3,131250,MRI,Original,sc,2018-12-26,Accelerated Sagittal IR-FSPGR,2018-12-27,DICOM,Brain,Both
237677,1119493,098_S_6655,ADNI 3,132900,MRI,Original,sc,2019-01-07,Sag Accel IR-FSPGR,2019-01-23,DICOM,Brain,Both
237708,1100527,027_S_6643,ADNI 3,131251,MRI,Original,sc,2018-12-26,Accelerated Sagittal IR-FSPGR,2018-12-27,DICOM,Brain,Both
...,...,...,...,...,...,...,...,...,...,...,...,...,...
273700,1668914,035_S_7120,ADNI 3,223783,MRI,Original,sc,2023-02-08,Accelerated Sagittal MPRAGE Phase A-P,2023-02-22,DICOM,Brain,Both
273718,1669252,035_S_7121,ADNI 3,223831,MRI,Original,sc,2023-02-15,Accelerated Sagittal MPRAGE Phase A-P,2023-02-22,DICOM,Brain,Both
273733,1679245,035_S_7123,ADNI 3,227360,MRI,Original,sc,2023-03-14,Accelerated Sagittal MPRAGE Phase A-P,2023-03-17,DICOM,Brain,Both
328948,10227031,153_S_6679,ADNI 3,236941,MRI,Original,sc,2019-01-28,Accelerated Sagittal MPRAGE,2023-05-22,DICOM,Brain,Both
336659,10239114,123_S_7125,ADNI 3,240466,MRI,Original,sc,2023-06-27,Sagittal 3D Accelerated MPRAGE,2023-06-28,DICOM,Brain,Both